"""move_position_column

Revision ID: 11e1f22a3519
Revises: 8ce40748bac2
Create Date: 2025-03-19 20:43:43.676944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11e1f22a3519'
down_revision: Union[str, None] = '8ce40748bac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_visualization_dataset_columns', 'position')
    op.add_column('report_visualizations', sa.Column('position', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_visualizations', 'position')
    op.add_column('report_visualization_dataset_columns', sa.Column('position', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
