"""create_neighborhoods_table

Revision ID: 462cdd0bfd72
Revises: 563b3c06de8a
Create Date: 2025-03-28 09:24:07.890839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462cdd0bfd72'
down_revision: Union[str, None] = '563b3c06de8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighborhoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=40, scale=20), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=40, scale=20), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neighborhoods')
    # ### end Alembic commands ###
