"""add_position_to_report_visualization_dataset_columns

Revision ID: 481bcdbb448d
Revises: eca01310c1f3
Create Date: 2025-02-25 19:48:46.603729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481bcdbb448d'
down_revision: Union[str, None] = 'eca01310c1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_visualization_dataset_columns', sa.Column('position', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_visualization_dataset_columns', 'position')
    # ### end Alembic commands ###
