"""add_geo_json_columns

Revision ID: 69be10d8a284
Revises: 462cdd0bfd72
Create Date: 2025-05-28 20:30:18.070264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69be10d8a284'
down_revision: Union[str, None] = '462cdd0bfd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('geo_json', sa.JSON(), nullable=True))
    op.add_column('states', sa.Column('geo_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'geo_json')
    op.drop_column('cities', 'geo_json')
    # ### end Alembic commands ###
