"""add_description_to_reports

Revision ID: 8c92bdeac143
Revises: d823bb41bbbd
Create Date: 2024-11-26 14:42:02.647613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c92bdeac143'
down_revision: Union[str, None] = 'd823bb41bbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'description')
    # ### end Alembic commands ###
