"""add_name_to_report_visualizations

Revision ID: ca28b3ec64cd
Revises: 481bcdbb448d
Create Date: 2025-03-03 16:31:36.079518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca28b3ec64cd'
down_revision: Union[str, None] = '481bcdbb448d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_visualizations', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_visualizations', 'name')
    # ### end Alembic commands ###
