name: Deploy FastAPI to GitHub Pages

on:
  push:
    branches:
      - master  # Altere para o branch que deseja usar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn

    - name: Run FastAPI app
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
